### ISSUE TITLE
Where to put the machinefiles to build this project?

### ISSUE THREAD

**Issue by pY4x3g** [Jutta-Proto/gtk-ui#1]
I was able to compile the bt-proto project, but I am not able to compile the gtk-ui. Where do I have to put the machinefiles?
I get: 
` Machine files not found.  Please make sure you read the chapter about
  machine files in the README.md first.`

But there is no such section in this project?

**Comment by COM8** [comment]
Please try placing them here: `gtk-ui/build/_deps/jutta_bt_proto-src/src/resources/machinefiles`
This is really something I should document better.

**Comment by pY4x3g** [comment]
ah i actually tried this, it did not work, because the _deps folder seems to be overwritten everytime I run cmake...

**Comment by COM8** [comment]
For me:
```bash
git clone git@github.com:Jutta-Proto/gtk-ui.git
cd  gtk-ui
mkdir build
cd build
cmake ..
# Copy the "machinefiles" directory to: "gtk-ui/build/_deps/jutta_bt_proto-src/src/resources/"
# Or "_deps/jutta_bt_proto-src/src/resources/" in case you are inside the build directory
cmake ..
cmake --build .
```

Then I can run as often as I want `cmake ..` without them disappearing again.

**Comment by COM8** [comment]
Did this fix your issue?
